### ISSUE TITLE
Command line flags

### ISSUE THREAD

**Issue by ondrej-fabry** [bmuschko/link-verifier#2]
The command line flags `-rootDirs` and `-includePatterns` are using _camelCase_ which is quite unusual for flags. You should also consider making them shorter, e.g. just `-dirs` and `-include`.

Now for the flag defaults:

- the flag `-rootDirs` with default as `content` might not really cover many of the use cases for developers. Actually, not many projects I worked with used `content` directory anywhere. I'd suggest using something like `.`, because I'm rather certain that general use case for this is to verify links in their entire repository. This is also default for most of, if not all, of the go tools.
- the flag `-includePatterns` doesn't have defaults even shown in the usage help (`-h`) and forces you to use the basic patterns without any option to change it. What if someone someone just wants to check _*.md_ files only?
- the flag `-fail` isn't currently very useful, because even if I set it to `false` the program [panic](https://github.com/bmuschko/link-verifier/blob/master/http/http.go#L29) after failing to connect to some URL.

**Comment by bmuschko** [comment]
I implemented all of your suggestions. Thanks again for identifying them. I released a new version in case you want to try it out.
