### ISSUE TITLE
--fail false flag is not recognised 

### ISSUE THREAD

**Issue by k8s-dev** [bmuschko/link-verifier#3]
Thanks @bmuschko for this tool!! Appreciate it.

ubuntu@ubuntu:~/workspace/docs$ link-verifier --fail false
Error: unknown command "false" for "link-verifier"
Run 'link-verifier --help' for usage.
unknown command "false" for "link-verifier"

whereas, the following works: 
ubuntu@ubuntu:~/workspace/docs$ link-verifier --fail=false
Searching text-based files in directories: .

-> Verifying file: README.md 

Will be submitting a PR to fix the documentation.

**Comment by bmuschko** [comment]
Looks like the handling for boolean flags in Cobra is slightly different than for other parameters. You are correct. It would need to be `--fail=false`.
